# Generated by Django 3.0.3 on 2023-01-09 19:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmem', models.CharField(max_length=50, verbose_name='使用者名稱')),
                ('bname', models.CharField(max_length=50, null=True, verbose_name='商品名稱')),
                ('num', models.CharField(max_length=20, verbose_name='數量')),
                ('ex', models.CharField(max_length=50, verbose_name='支出')),
                ('left', models.CharField(max_length=50, verbose_name='剩餘點數')),
                ('bid', models.UUIDField(default=uuid.uuid4, verbose_name='訂單編號')),
                ('bdate', models.DateTimeField(auto_now_add=True, verbose_name='兌換日期')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHONE', models.CharField(max_length=10, verbose_name='手機')),
                ('NAME', models.CharField(max_length=10, verbose_name='姓名')),
                ('PASSWORD', models.CharField(max_length=20, verbose_name='密碼')),
                ('NICKNAME', models.CharField(max_length=20, verbose_name='暱稱')),
                ('POINT', models.CharField(blank=True, max_length=30, null=True, verbose_name='點數')),
                ('IDCARD', models.CharField(max_length=10, verbose_name='身分證')),
            ],
        ),
        migrations.CreateModel(
            name='qa',
            fields=[
                ('MEMID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='會員ID')),
                ('DISC', models.TextField(default='', max_length=255, verbose_name='問題描述')),
                ('IMAGE', models.ImageField(blank=True, default='', max_length=1000, upload_to='', verbose_name='上傳圖片')),
                ('RDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送出日期')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='REWARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_ID', models.CharField(max_length=50, verbose_name='商品ID')),
                ('R_NAME', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('R_IMG', models.ImageField(upload_to='static/images', verbose_name='商品img')),
                ('R_CONTENT', models.CharField(default='', max_length=50, verbose_name='商品內容')),
                ('COSTPOINT', models.CharField(default='', max_length=50, verbose_name='商品點數')),
                ('ALERT', models.CharField(default='', max_length=50, verbose_name='兌換警告')),
            ],
        ),
    ]
