# Generated by Django 3.0.3 on 2023-01-09 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230110_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 20, 12, 35, 545087, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
