# Generated by Django 3.0.3 on 2023-01-10 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230110_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 4, 2, 36, 353818, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
