# Generated by Django 3.0.3 on 2023-01-10 06:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230110_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=50, verbose_name='訂單編號')),
                ('MEMID', models.CharField(default='', max_length=50, verbose_name='使用者編號')),
                ('APPID', models.CharField(default='', max_length=50, verbose_name='APP編號')),
                ('C_AMOUNT', models.CharField(default='', max_length=50, verbose_name='花費碳稅')),
                ('GPOINT', models.IntegerField(verbose_name='獲得點數')),
                ('AMOUNT', models.CharField(default='', max_length=50, verbose_name='消費總金額')),
                ('CDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='成立時間')),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 6, 28, 0, 860828, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
