# Generated by Django 3.0.3 on 2023-01-10 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230110_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 13, 41, 38, 946143, tzinfo=utc), verbose_name='兌換日期'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='ex',
            field=models.IntegerField(verbose_name='支出'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='left',
            field=models.IntegerField(verbose_name='剩餘點數'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='num',
            field=models.IntegerField(verbose_name='數量'),
        ),
    ]
