# Generated by Django 3.0.3 on 2023-01-10 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 18, 11, 6, 218856, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
