# Generated by Django 3.0.3 on 2023-01-11 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230111_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FKcheck', models.CharField(default=myapp.models.UUIDrand, max_length=36)),
                ('Rstate', models.CharField(max_length=42)),
                ('Raccesscode', models.CharField(max_length=43)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=100)),
                ('ACCESSCODE', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 12, 35, 52, 767237, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
