# Generated by Django 3.0.3 on 2023-01-12 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230111_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 6, 58, 36, 736339, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
