# Generated by Django 3.0.3 on 2023-01-12 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20230112_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 7, 3, 3, 538857, tzinfo=utc), verbose_name='兌換日期'),
        ),
    ]
